services:
  postgres:
    image: postgres:16
    container_name: hortifruti-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-hortifruti}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Your_password123}
      POSTGRES_DB: ${POSTGRES_DB:-hortifruti_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: ./api/Hortifruti.Api
    container_name: hortifruti-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=${POSTGRES_DB:-hortifruti_db};Username=${POSTGRES_USER:-hortifruti};Password=${POSTGRES_PASSWORD:-Your_password123}
      Jwt__SecretKey: ${JWT_SECRET_KEY:-alter-me-para-um-segredo-super-seguro-2025}
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres-data:
